### PR TITLE
Kta matrix nio integration

### PR DESCRIPTION
**Pull request by ktaylora**
Bot is deployable -- going to work on pluggin-in some of the backends next. Will cover in another PR.

### CODE REVIEW

**Comment by xloem** [comment]
I'm glad you got it running.

To repeat, the matrix code that's in there is using the older `matrix_client` and `matrox_bot_api`, _not_ matrix-nio yet.

**Review by xloem — APPROVED** [review]

**Comment by xloem** [comment]
what are you using for automated code formatting?

**Comment by ktaylora** [comment]
Black https://pypi.org/project/black/

**Comment by ktaylora** [comment]
> I'm glad you got it running.
> 
> To repeat, the matrix code that's in there is using the older `matrix_client` and `matrox_bot_api`, _not_ matrix-nio yet.

Odd. I'm only installing the nio package from the package index. I did notice that the main event loop is not async (nio code examples all use decorators). It's still using a while-loop and polling for changes in state. Like to change that.

But... don't really care. As long as the bot can join a channel and send/receive messages, that's all it needs to do. The backends are the cool part.

**Pull request merged**
